### ISSUE TITLE
Not easily available for VS Code on Arch and Manjaro Linux

### ISSUE THREAD

**Issue by MareinK** [theacodes/witchhazel#10]
Hi! It seems that the default VS Code package in Arch and Manjaro [has switched (?) to using Open VSX rather than the VS Marketplace](https://wiki.archlinux.org/index.php/Visual_Studio_Code#No_extensions_found). Since witchhazel is not on [Open VSX](https://open-vsx.org/), it is not very easily available for VS Code on Arch and Manjaro now. There is a workaround: [download the extension](https://marketplace.visualstudio.com/items?itemName=TheaFlowers.witch-hazel) and [install it manually](https://github.com/microsoft/vscode/issues/108147#issuecomment-704723949). However, it would be easier if the extension was available inside VS Code directly on these platforms, too. Would you be interested in providing it on Open VSX so we can enjoy the extension with convenience? :)

**Comment by theacodes** [comment]
Hi, it's published there now.
https://open-vsx.org/extension/TheaFlowers/witch-hazel

**Comment by MareinK** [comment]
Awesome, thanks!!
