### ISSUE TITLE
Add 'active indent guide' color (VS Code)

### ISSUE THREAD

**Issue by MareinK** [theacodes/witchhazel#11]
VS Code (maybe as well as other supported IDEs?) has a feature where it can highlight the active indent guide, which I think it very handy. I noticed this feature is lost in the current `witchhazel` theme, because both the inactive and active guides get the same color. I propose to add a custom color to the active indent guide.

I was able to get a custom color by adding the below to my settings. (the `background` is the existing guide color, the `activeBackground` is the 'rouge' color from the vim implementation as well as the 'Error' color from the Python implementation)

```json
"workbench.colorCustomizations": {
  "editorIndentGuide.background": "#A8757B",
  "editorIndentGuide.activeBackground": "#960050"
}
```

I'm not sure whether just pasting those into the theme file will do the trick. In any case, the result is this:

![image](https://user-images.githubusercontent.com/1388357/99240574-f88a7f00-27fc-11eb-851d-a2cc46148d89.png)

Let me know what you think!

**Comment by theacodes** [comment]
Totally for this, but I'd definitely want a different set of colors for those guides. Let me think on it a bit
