### ISSUE TITLE
colored diff decorations in scrollbar hidden under opaque black (Hypercolor)

### ISSUE THREAD

**Issue by ansemjo** [theacodes/witchhazel#13]
I'm not sure how to call these things but when you're looking at a diff there are coloured decorations in the scrollbar, indicating additions and deletions.

![image](https://user-images.githubusercontent.com/11139925/109033250-bc519f00-76c6-11eb-9f94-ac4a1f7393e6.png)

These are completely hidden under the opaque black scrollbar of the **Hypercolor** theme variant. Of course it's not that great of an issue because the only case when any scrollbar decorations are hidden, is when the corresponding changes are currently in view ... still. Is this intended?

I'm also not sure how one would fix that. Can you change the layer order of these decorations or the scrollbar itself? Or just reduce the opacity a little bit?

**Comment by theacodes** [comment]
Could you show me a screenshot with a little more context? It'd also be useful to see a screenshot of a theme where this isn't an issue.

**Comment by ansemjo** [comment]
Of course, sorry.

Here is the main window on a simple diff:
![image](https://user-images.githubusercontent.com/11139925/109036871-5b2bca80-76ca-11eb-8887-6f615b7d51dd.png)

Note the big black scrollbar in the top right corner. If I scroll down a little bit, the red and green colored decorations appear in its place:
![image](https://user-images.githubusercontent.com/11139925/109037046-8d3d2c80-76ca-11eb-8a29-cb805264ee60.png)

It is, for example, not a problem with the default variant of this very theme – it is only the Hypercolor variant that has this opaque scrollbar:
![image](https://user-images.githubusercontent.com/11139925/109037185-bd84cb00-76ca-11eb-8431-3ab922412bc0.png)

**Comment by theacodes** [comment]
Cool, this is fix in 2021.2.24, which is working its way through the publishing pipeline. :)
