### ISSUE TITLE
[VSCodium] Invisible current line in Hypercolor

### ISSUE THREAD

**Issue by Shadlock0133** [theacodes/witchhazel#14]
![image](https://user-images.githubusercontent.com/3766527/125786187-35db058a-e92c-4ee3-b9c5-1fbc0797aeea.png)
In above picture, selected line "Install Extensions" (using keyboard) has the same color as background.

**Comment by Shadlock0133** [comment]
For now, I've worked around this issue by add this in `settings.json`:
```json
"workbench.colorCustomizations": {
    "[Witch Hazel Hypercolor]": {
        "quickInputList.focusBackground": "#8077A8"
    }
}
```

**Comment by theacodes** [comment]
I wonder what's different with VSCodium vs VS Code that's causing this. If anyone has any ideas, let me know.
