### ISSUE TITLE
Xcode theme

### ISSUE THREAD

**Issue by noisypigeon** [theacodes/witchhazel#17]
I've never made a theme but I'm happy to research it and do it. Where would I find the colour values? Have you ever made an Xcode theme and know how to do it? haha, thanks! love the theme.

**Comment by theacodes** [comment]
Go for it! The `tmTheme` is the best starting point:

* https://github.com/theacodes/witchhazel/blob/master/witchhazel.tmTheme
* https://github.com/theacodes/witchhazel/blob/master/witchhazelhypercolor.tmTheme

**Comment by noisypigeon** [comment]
Thank you! Working on it in #18. Not ready yet, will post when it is.
