### ISSUE TITLE
Pygments unable to load witchhazel style

### ISSUE THREAD

**Issue by ucodery** [theacodes/witchhazel#34]
## What is this issue about?
The wheel from pypi seems to be missing the required entry_point.

Are you 

- [x] reporting a bug
- [ ] suggesting a new **feature for an existing editor theme**
- [ ] suggesting this theme for a **new editor that is not yet supported**

## Which editor does this issue concern?

- [ ] VS Code
- [ ] Sublime
- [ ] JetBrains
- [ ] Atom
- [x] Pygments
- [ ] Other: ________

## Which theme variant(s) does this issue concern:

- [x] Classic
- [ ] Hypercolor

## Screenshots

```python
Python 3.10.5 (main, Jul 13 2022, 05:21:13) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata
>>> importlib.metadata.version('witchhazel')
'2018.8.23'
>>> importlib.metadata.entry_points(group='pygments.styles')
[]
>>> importlib.metadata.distribution('witchhazel').entry_points
[]
>>> import pygments.styles
>>> pygments.styles.get_style_by_name('witchhazel')
Traceback (most recent call last):
  File "/Users/ucodery/.pyenv/versions/blog/lib/python3.10/site-packages/pygments/styles/__init__.py", line 82, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.witchhazel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ucodery/.pyenv/versions/blog/lib/python3.10/site-packages/pygments/styles/__init__.py", line 84, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'witchhazel'.
```

Also tried installing from sdist and from source with the same results.

**Comment by theacodes** [comment]
Hi! Looks like somehow the distribution uploaded to PyPI didn't have the `entry_points.txt` file that's supposed to be there. I uploaded a new version that should work: https://pypi.org/project/witchhazel/2022.9.8/

Let me know if you run into any other trouble.

**Comment by ucodery** [comment]
It's working now, thanks for the quick turn around!
