### ISSUE TITLE
Icon for VSCode extension

### ISSUE THREAD

**Issue by nopjmp** [theacodes/witchhazel#4]
If I find time, I might look at creating an icon for the extension so it's easier to find for folks. This issue is to discuss what an icon for witchhazel would look like.

**Comment by theacodes** [comment]
I'd love to commission one of my artist friends to draw something.

Maybe just a cute lil witch?

**Comment by nopjmp** [comment]
A cute lil witch sounds amazing actually or a witch cat.

**Comment by theacodes** [comment]
Cool. I've commissioned an artist. Will update once we've got an icon. :)
