### ISSUE TITLE
Lua port for neovim

### ISSUE THREAD

**Issue by exoess** [theacodes/witchhazel#41]
Wondering if you'd be willing to write a lua port of the vim colorscheme for neovim, if not I could prolly do it

**Comment by exoess** [comment]
I actually just finished porting it, there seem to be a few missing colors in my version tho, if you could look it over that'd be great

**Comment by theacodes** [comment]
Send a pull request! :)

**Comment by exoess** [comment]
I don't actually know how lol

**Comment by theacodes** [comment]
That's okay! If you'd like to learn you can start here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models

**Comment by exoess** [comment]
i figured it out :3

**Comment by exoess** [comment]
quick question, is there a version of this colorscheme for terminals?

**Comment by exoess** [comment]
forgot to close lol
