### ISSUE TITLE
SCM highlight

### ISSUE THREAD

**Issue by FernandoMiguel** [theacodes/witchhazel#48]
## What is this issue about?
I absolute adore this theme.
But I find the highlight of the SCM to bright making the buttons unreadble

Are you 

- [ ] reporting a bug
- [X] suggesting a new **feature for an existing editor theme**
- [ ] suggesting this theme for a **new editor that is not yet supported**

## Which editor does this issue concern?

- [X] VS Code
- [ ] Sublime
- [ ] JetBrains
- [ ] Atom
- [ ] Pygments
- [ ] Other: ________

## Which theme variant(s) does this issue concern:

- [ ] Classic
- [X] Hypercolor

## Screenshots
![image](https://github.com/theacodes/witchhazel/assets/168366/55508ebe-ebca-49af-94f3-cf784a57785b)

**Comment by theacodes** [comment]
Thanks! I fixed this and it's been published to the VSCode marketplace, it might take a bit for it to roll out.

**Comment by FernandoMiguel** [comment]
Wow
Such a quick response.
9 I was definitely not expecting this to be fixed so soon.
Thank you so much
