### ISSUE TITLE
Class base jarring?

### ISSUE THREAD

**Issue by MareinK** [theacodes/witchhazel#6]
Hey, I really like this theme! Just one thing I find rather jarring: the yellow colour and underlining for the base of a class, see below.

![image](https://user-images.githubusercontent.com/1388357/69868492-2142fd00-12aa-11ea-9c87-97b8f45377e2.png)

I'd like to hear whether it's just me :) This is in VS Code.

**Comment by theacodes** [comment]
Which editor are you using?

**Comment by MareinK** [comment]
I'm using VS Code.

**Comment by theacodes** [comment]
It is supposed to be Yellow (though I'm open to changing the color), but it
shouldn't be underlined. If you'd like to send a PR to fix it I'd be happy
to accept it!

**Comment by MareinK** [comment]
I gave it a try and removing the underline makes it a lot better I think :)
